# Generated by Django 4.0.6 on 2022-07-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('price', models.IntegerField()),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('joined_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.newsletter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registeration.user')),
            ],
        ),
    ]
