# Generated by Django 4.0.6 on 2022-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
